##
## AppVeyor
## https://www.appveyor.com/
##

version: "{build}"

# VS 2013 image = VS 2010 build
image:
 - Visual Studio 2013
 - Ubuntu

platform:
 - x32

matrix:
 allow_failures:
  - image: Ubuntu
  - image: Visual Studio 2015
  - image: Visual Studio 2017
  - platform: x64

for:
 - matrix:
    only:
     - image: Ubuntu
     - image: Ubuntu1604
     - image: Ubuntu1804
   clone_folder: /FOC
 - matrix:
    only:
     - image: Visual Studio 2013
     - image: Visual Studio 2015
     - image: Visual Studio 2017
   clone_folder: C:\FOC

cache:
 - Cache -> CMakeLists.txt, Source/Extensions/CMakeLists.txt, Build.cmake, Pack.cmake

install:
 - git submodule update --init --recursive
 - cmd: set PATH=Cache\cmake\bin;%PATH%
 - cmake -DO=Build.cmake;Pack.cmake;Source/Engine/Build.cmake -DOWNLOAD_DIR=Cache -P Source/Engine/CMake/SelfUpdate/SelfUpdate.cmake

build_script:
 - cmake -P Build.cmake
 - cmake -P Pack.cmake

artifacts:
 - path: FOC*.zip
