##
## AppVeyor
## https://www.appveyor.com/
##

version: "{build}"

# VS 2013 image = VS 2010 build
image:
 - Visual Studio 2013
 - Ubuntu1804

platform:
 - x32

matrix:
 allow_failures:
  - image: Ubuntu1804
  - image: Visual Studio 2015
  - image: Visual Studio 2017
  - platform: x64

for:
 - matrix:
    only:
     - image: Ubuntu
     - image: Ubuntu1604
     - image: Ubuntu1804
   clone_folder: /FOC
 - matrix:
    only:
     - image: Visual Studio 2013
     - image: Visual Studio 2015
     - image: Visual Studio 2017
   clone_folder: C:\FOC

cache:
 - Cache -> CMakeLists.txt, Source/Extensions/CMakeLists.txt, Build.cmake, Pack.cmake

init:
 - sh: if [ "${PLATFORM}" == "x32" ]; then arch=i386; else arch=amd64; fi

install:
 - git submodule update --init --recursive
 - sh: sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
 - sh: sudo apt-get update
 - sh: sudo apt-get install -y gcc-multilib g++-multilib
 - sh: sudo apt-get install -y libx11-dev:${arch} libxft-dev:${arch} libxi-dev:${arch} libxinerama-dev:${arch} libllvm6.0:${arch} libgl1-mesa-dri:${arch} libgl1-mesa-glx:${arch} libgl1-mesa-dev:${arch} libglu1-mesa:${arch} libglu1-mesa-dev:${arch} freeglut3:${arch} freeglut3-dev:${arch} libfreetype6-dev:${arch} libfontconfig-dev:${arch} libpng-dev:${arch}
 - sh: PATH=Cache/cmake/bin:$PATH
 - cmd: set PATH=Cache\cmake\bin;%PATH%
 - cmake -DO="Build.cmake;Pack.cmake;Source/Engine/Build.cmake" -DOWNLOAD_DIR=Cache -P Source/Engine/CMake/SelfUpdate/SelfUpdate.cmake
 - sh: hash -r

build_script:
 - sh: ln -s Source/Engine/CMake CMake
 - cmake -P Build.cmake
 - cmake -P Pack.cmake

artifacts:
 - path: FOC*.zip
